g

diff --git a/asdf/get-version/action.yml b/asdf/get-version/action.yml
--- a/asdf/get-version/action.yml
+++ b/asdf/get-version/action.yml
@@ -16,5 +16,10 @@ runs:
   using: composite
   steps:
     - id: get-version
+      shell: sh
       run: echo "::set-output name=plugin-version::$(cat .tool-versions | grep ${{ inputs.plugin-name }} | cut -d' ' -f2)"
-      shell: bash
+    - shell: sh
+      run: |
+        echo "${{ inputs.plugin-name }} version not found. Make sure that .tool-versions exists and ${{ inputs.plugin-name }} version is specified in it"
+        exit 1
+      if: ${{ steps.get-version.outputs.plugin-version }} == ""
